version: "3.9"  
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: web:2.0
    ports:
      - "82:5000"
    restart: always
    networks:
      - webnet

networks:
  webnet: